   services:
     - type: web
       name: leech-bot
       env: python
       buildCommand: "pip install -r requirements.txt"
       startCommand: "gunicorn -w 4 bot:app -b 0.0.0.0:5000"
       # Add these environment variables if needed
       envVars:
         - key: TELEGRAM_BOT_TOKEN
           value: ${TELEGRAM_BOT_TOKEN}
   
