   services:
     - type: web
       name: leech-bot
       env: python
       buildCommand: "pip install -r requirements.txt"
       startCommand: "python bot.py"  # Ensure this matches your main bot file
       # Add these environment variables if needed
       envVars:
         - key: TELEGRAM_BOT_TOKEN
           value: ${TELEGRAM_BOT_TOKEN}
   
